server:
  port: 8081
spring:
  application:
    name: order
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/
info:
  app:
    name: "Product Service"
    description: "Product management service"
    version: 1.0.0

